name: Pipeline de CI - analytics-service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: FIAP-Teach-Challenge-2/toggle-master-ci/.github/workflows/reusable-ci-python.yml@main
    with:
      service-name: analytics-service
      ecr-repository: togglemaster/analytics-service
    secrets: inherit
